[package]
name = "ructl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }

protokit = { path = "../../protokit/protokit" }

rubeapi = { path = "../rubeapi" }
